version: '3'
services:
  knowledge-game-app:
    build:
      context: /home/pablojakub/Projects/KnowledgeGame
      dockerfile: Dockerfile
    restart: unless-stopped
    privileged: true
networks:
  default:
    external: true
    name: scoobydoo
